// Maridew Holdings Ltd — site content, rendered dynamically by main.js
window.SITE_DATA = {
  company: {
    name: "Maridew Holdings Ltd",
    tagline: "Integrated Land, Infrastructure & Built Environment Solutions",
    motto: "From Land to Legacy — We Build What Endures",
    location: "Nairobi, Kenya | East Africa",
  },

  pillars: [
    {
      n: "01",
      title: "Land & Property Intelligence",
      desc: "Advisory, due diligence, legal support and strategic insight across the Kenyan land market.",
    },
    {
      n: "02",
      title: "Geospatial & Survey Sciences",
      desc: "Precision surveying, mapping, GIS and terrain analysis underpinning all project decisions.",
    },
    {
      n: "03",
      title: "Ground Engineering & Site Science",
      desc: "Geotechnical investigation and site suitability analysis for safe and informed development.",
    },
    {
      n: "04",
      title: "Planning, Design & Regulatory Navigation",
      desc: "Physical planning, architectural design and development approval support.",
    },
    {
      n: "05",
      title: "Civil & Infrastructure Engineering",
      desc: "Roads, drainage, water, sewer and all site infrastructure engineered to last.",
    },
    {
      n: "06",
      title: "Sewage & Wastewater Management",
      desc: "Sewage collection, treatment, disposal and wastewater infrastructure for all development types.",
    },
    {
      n: "07",
      title: "Construction, Supervision & Quality Delivery",
      desc: "On-site technical oversight, project management and quality assurance throughout construction.",
    },
    {
      n: "08",
      title: "Real Estate & Asset Management",
      desc: "Property development, investment advisory, estate packaging and long-term asset value optimization.",
    },
    {
      n: "09",
      title: "Agricultural & Water Infrastructure",
      desc: "Irrigation engineering, farm water systems and productive-land infrastructure for agribusinesses.",
    },
  ],

  // phase groups the 16 divisions into the value chain for filtering
  phases: {
    "01": "Assess",
    "02": "Assess",
    "03": "Assess",
    "04": "Plan",
    "05": "Plan",
    "06": "Plan",
    "07": "Design",
    "08": "Design",
    "09": "Design",
    "10": "Design",
    "11": "Deliver",
    "12": "Deliver",
    "13": "Realise",
    "14": "Realise",
    "15": "Sustain",
    "16": "Sustain",
  },

  divisions: [
    {
      n: "01",
      title: "Land Services & Land Administration",
      summary:
        "End-to-end advisory and support across the entire land ownership, transaction and development readiness cycle.",
      items: [
        "Land acquisition advisory and investment sourcing",
        "Land identification, sourcing, purchase and sale support",
        "Land transfer and title deed processes",
        "Land subdivision and amalgamation",
        "Land inheritance and succession support relating to land assets",
        "Land ownership verification and title deed due diligence",
        "Land registry support and land search through Kenyan systems",
        "Historical land records and ownership tracing",
        "Easement and right-of-way guidance",
        "Land dispute coordination with relevant legal professionals",
        "Land valuation coordination",
        "Development and land use suitability assessments",
        "Land banking and strategic land investment advisory",
      ],
    },
    {
      n: "02",
      title: "Land Surveying, Mapping & Geo-Spatial Services",
      summary:
        "Comprehensive surveying, mapping and geospatial intelligence to support planning, design, construction and registration.",
      items: [
        "Topographical and cadastral surveys",
        "Boundary surveys and boundary re-establishment",
        "Subdivision and amalgamation surveys",
        "Site setting out for projects",
        "As-built and engineering surveys",
        "Route alignment surveys for roads and utilities",
        "GPS / GNSS surveying",
        "Drone mapping and aerial site mapping",
        "GIS mapping and land information mapping",
        "Contour mapping and terrain modeling",
        "Utility mapping and underground service mapping",
        "Digital mapping and survey data processing",
      ],
    },
    {
      n: "03",
      title: "Geotechnical, Geological & Site Investigation Services",
      summary:
        "Ground investigation and soil analysis to guide foundation design and confirm site suitability for development.",
      items: [
        "Geotechnical investigations and soil profiling",
        "Soil bearing capacity determination",
        "Borehole drilling for geotechnical assessment",
        "Trial pits and field sampling",
        "Laboratory testing of soil and construction materials",
        "Foundation type recommendations",
        "Slope stability assessment",
        "Groundwater and drainage condition assessment",
        "Pavement subgrade investigations",
        "Site suitability studies for buildings, roads and infrastructure",
        "Earthworks suitability assessment",
      ],
    },
    {
      n: "04",
      title: "Physical Planning, Land Use Planning & Development Approvals",
      summary:
        "Converting raw land into legally and technically developable land through planning, zoning and regulatory compliance support.",
      items: [
        "Land use and physical planning advisory",
        "Development planning, concept planning and site planning",
        "Master planning for estates and mixed-use developments",
        "Plot planning and subdivision planning",
        "Development control advisory",
        "Change-of-user and extension-of-user support",
        "Planning approvals and county approval process coordination",
        "Building permit support",
        "Environmental and planning compliance coordination",
        "Infrastructure planning for estates and institutions",
      ],
    },
    {
      n: "05",
      title: "Architecture & Built Environment Design",
      summary:
        "Full architectural design services from concept through to construction documentation, for all building typologies.",
      items: [
        "Architectural concept and schematic design",
        "Residential, commercial and institutional building design",
        "Hospitality and mixed-use development design",
        "Renovation, remodeling and adaptation design",
        "Space planning and functional layout optimization",
        "Building presentation drawings and 3D concept visuals",
        "Construction drawings and detailing",
        "Building approvals documentation support",
        "Sustainable and climate-responsive building design",
      ],
    },
    {
      n: "06",
      title: "Structural Engineering Services",
      summary:
        "Structural analysis, design, detailing and site support for all building types and infrastructure structures.",
      items: [
        "Structural design of buildings — reinforced concrete, steel and masonry",
        "Foundation and retaining wall design",
        "Water tank support structures",
        "Industrial and warehouse structures",
        "Structural analysis and calculations",
        "Structural assessments and integrity reviews",
        "Rehabilitation and structural strengthening design",
        "Structural drawings and detailing",
        "Site structural supervision support",
        "Temporary works and support structure design where applicable",
      ],
    },
    {
      n: "07",
      title: "Civil Engineering & Infrastructure Development",
      summary:
        "Core civil engineering and infrastructure design for estates, institutions, roads, and public/private projects.",
      items: [
        "Civil engineering consultancy and site infrastructure planning",
        "Earthworks and grading design",
        "Stormwater drainage design",
        "Sewer and sanitation infrastructure design",
        "Sewage waste management systems design and implementation",
        "Sewage collection, conveyance and disposal infrastructure",
        "Access roads, road design and construction support",
        "Pavement design",
        "Culverts, drainage structures and bridges",
        "Estate and industrial infrastructure design",
        "Utility corridor planning",
        "Site servicing and external works design",
      ],
    },
    {
      n: "08",
      title: "MEP Engineering & Building Services",
      summary:
        "Integrated mechanical, electrical and public health engineering for all building and development typologies.",
      items: [
        "Plumbing, water reticulation and drainage design",
        "HVAC and ventilation systems design",
        "Firefighting and suppression systems",
        "Pumping systems and water storage design",
        "Electrical installations and power distribution design",
        "Lighting systems design",
        "Backup power and solar integration coordination",
        "Earthing and lightning protection systems",
        "Sewer reticulation and sewage waste management systems",
        "Septic tank, biodigester and on-site sewage treatment design",
        "Wastewater treatment and effluent disposal systems",
        "Rainwater harvesting and water efficiency systems",
      ],
    },
    {
      n: "09",
      title: "Roads, Transport & Access Infrastructure",
      summary:
        "Transportation-related civil works, access planning and road project support for all development types.",
      items: [
        "Access road planning, design and construction support",
        "Internal estate roads and rural feeder roads",
        "Driveways, parking layouts and traffic circulation planning",
        "Pavement rehabilitation advisory",
        "Road drainage and culvert design",
        "Road project supervision support",
        "Materials and quantities estimation for road works",
      ],
    },
    {
      n: "10",
      title: "Water, Irrigation & Agricultural Infrastructure",
      summary:
        "Agricultural engineering, water systems and farm infrastructure connecting land to productive use.",
      items: [
        "Irrigation systems design — drip, sprinkler and surface",
        "Farm water distribution systems",
        "Borehole water infrastructure support",
        "Water storage solutions for farms and developments",
        "Pump selection and irrigation pumping systems",
        "Small dam and water harvesting support",
        "Agricultural land infrastructure planning",
        "Farm roads and access planning",
        "Greenhouse and productive-land support infrastructure",
        "Drainage planning for agricultural land",
        "Land productivity enhancement infrastructure",
      ],
    },
    {
      n: "11",
      title: "Building Construction, Project Execution & Site Support",
      summary:
        "Technical site representation, construction management support and quality oversight throughout project delivery.",
      items: [
        "Construction project planning and management support",
        "Site supervision and inspection",
        "Clerk-of-works and resident technical representation",
        "Project coordination among consultants and contractors",
        "Quality control and quality assurance support",
        "Materials planning and technical review",
        "Construction methodology review",
        "Progress monitoring and reporting",
        "Snagging and defects inspection",
        "Practical completion and handover support",
        "Post-completion maintenance planning support",
      ],
    },
    {
      n: "12",
      title: "Project Management, Cost Management & Development Advisory",
      summary:
        "Strategic, commercial and management services that guide projects from inception through to successful delivery.",
      items: [
        "Project management consultancy",
        "Development advisory and feasibility studies",
        "Technical due diligence",
        "Project budgeting and cost planning support",
        "Bills of quantities coordination",
        "Procurement support and tender documentation coordination",
        "Tender evaluation support",
        "Contract administration coordination",
        "Project scheduling and progress tracking",
        "Risk management for development projects",
        "Investment-focused project appraisal",
      ],
    },
    {
      n: "13",
      title: "Real Estate, Property Development & Asset Services",
      summary:
        "Turning land and buildings into viable, investment-grade property assets across all sectors.",
      items: [
        "Real estate and property development planning",
        "Residential estate and commercial property development",
        "Mixed-use development planning",
        "Land and property investment advisory",
        "Property acquisition support",
        "Property sales and marketing coordination",
        "Property management support",
        "Rental property planning and optimization",
        "Estate infrastructure packaging and serviced plot development",
        "Asset improvement and redevelopment strategy",
        "Real estate feasibility and highest-best-use analysis",
      ],
    },
    {
      n: "14",
      title: "Interior Design, Finishes & Landscaping",
      summary:
        "Enhancing the spatial quality, aesthetic character and external environment of completed developments.",
      items: [
        "Interior space planning and concept design",
        "Office, residential, hospitality and institutional interiors",
        "Finishes specification and furniture and fit-out coordination",
        "Lighting and interior ambiance planning",
        "Interior refurbishment and upgrades",
        "Landscape design — soft and hard landscaping",
        "Outdoor recreational and garden design",
        "Estate beautification and site external aesthetics integration",
        "Water features and outdoor amenity planning",
      ],
    },
    {
      n: "15",
      title: "Environmental, Sustainability & Compliance Support",
      summary:
        "Embedding environmental responsibility and long-term sustainability into every phase of land and infrastructure development.",
      items: [
        "Environmental planning and EIA compliance coordination",
        "Stormwater and drainage sustainability strategies",
        "Water conservation planning",
        "Sustainable site development advisory",
        "Green building support",
        "Climate-responsive infrastructure planning",
        "Sewage and wastewater management advisory",
        "Effluent treatment, disposal and environmental compliance",
        "Solid and liquid waste management infrastructure planning",
        "Resource-efficient development recommendations",
        "Resilience and long-term infrastructure sustainability planning",
      ],
    },
    {
      n: "16",
      title: "Specialized & Integrated Support Services",
      summary:
        "Complementary technical and commercial services that extend the firm's reach across the built environment value chain.",
      items: [
        "Property and infrastructure maintenance services",
        "Facilities management support",
        "Infrastructure rehabilitation and upgrades",
        "Construction materials supply coordination",
        "Technical documentation and design reporting",
        "CAD drafting and BIM coordination",
        "Permit and statutory approval facilitation support",
        "Utility connection coordination",
        "Turnkey development packaging",
        "Public-private development support",
        "Institutional and church project development support",
        "Industrial yard and warehouse development",
        "Site audits and condition assessments",
        "Land and infrastructure investment partnership facilitation",
      ],
    },
  ],

  clients: [
    "Private Landowners",
    "Real Estate Developers",
    "Homeowners",
    "Institutions — Schools, Colleges, Hospitals & Government Agencies",
    "Churches & Faith-based Organizations",
    "Farmers & Agribusiness Investors",
    "Contractors & Construction Firms",
    "County Governments & Municipalities",
    "NGOs & Development Partners",
    "Commercial Investors & Private Equity",
    "Industrial Clients",
    "Diaspora & International Investors",
  ],

  valueProps: [
    {
      title: "Integrated One-Stop Expertise",
      desc: "Clients engage a single, accountable partner for every stage — from land identification and feasibility through engineering, sewage management, construction and property management.",
    },
    {
      title: "Full Land Value Chain Capability",
      desc: "Very few firms in Kenya can genuinely serve clients from raw land acquisition through due diligence, survey, planning, engineering, sewage infrastructure and real estate asset management.",
    },
    {
      title: "Kenya-Specific Market Intelligence",
      desc: "Deep knowledge of Kenya's land registration systems, county planning frameworks, development approval processes and real estate market dynamics gives clients a decisive advantage.",
    },
    {
      title: "Credibility Across Disciplines",
      desc: "Specialist-grade expertise within each of its sixteen divisions — including dedicated sewage and wastewater engineering capability — rather than breadth at the expense of depth.",
    },
    {
      title: "Investor & Institutional Ready",
      desc: "Corporate structure, professional documentation standards and multi-disciplinary scope make Maridew the right partner for institutional investors, DFIs, county governments and large-scale developers.",
    },
    {
      title: "Commitment to Sustainability",
      desc: "Environmental responsibility embedded into every discipline — from sewage waste management and wastewater treatment through drainage design, materials selection and agricultural infrastructure.",
    },
  ],

  taglines: [
    "From Land to Legacy — We Build What Endures",
    "Integrated Land and Infrastructure Solutions for Africa's Future",
    "One Partner. Every Stage. Every Project.",
    "Where Land Meets Vision, and Vision Becomes Reality",
    "Shaping Land. Engineering Infrastructure. Creating Value.",
    "Your End-to-End Built Environment Partner",
    "Land Intelligence. Infrastructure Excellence. Property Value.",
    "Built for Kenya. Designed to Last.",
    "From the First Survey to the Final Key",
    "Transforming Land Into Living, Working and Growing Environments",
  ],

  subsidiaries: [
    { name: "Maridew Survey & Geospatial Ltd", focus: "Land surveying, drone mapping and GIS services" },
    { name: "Maridew Engineering Consultants Ltd", focus: "Civil, structural and MEP engineering consultancy" },
    { name: "Maridew Realty Ltd", focus: "Real estate development, property sales and asset management" },
    { name: "Maridew Irrigation & Water Systems Ltd", focus: "Agricultural water infrastructure and irrigation solutions" },
    { name: "Maridew Infrastructure Ltd", focus: "Roads, civil infrastructure and construction management" },
    { name: "Maridew Interiors & Landscapes Ltd", focus: "Interior design, finishes and landscape architecture" },
    { name: "Maridew Project Management Ltd", focus: "Project management, cost consultancy and development advisory" },
    { name: "Maridew Geotechnics Ltd", focus: "Site investigations, soil testing and geotechnical reporting" },
    { name: "Maridew Wastewater & Environmental Ltd", focus: "Sewage waste management, wastewater treatment and environmental compliance" },
  ],
};
